### ISSUE TITLE
Args that are in the stack are incorrect or missing

### ISSUE THREAD

**Issue by tomsons26** [VGKintsugi/Ghidra-SegaSaturn-Processor#1]
In the Saturn sdk \SAMPLE\S_9_1\SCL_FUNC.C the function Map2VRAM has the args ( Uint16 *Map_Data , Uint32 Map_Adr , Uint16 suuj , Uint16 suui , Uint16 palnum ,Uint32 mapoff) but Ghidra decompiles it with the first 4 args and rest go missing, instead the code has weird unaff_r# in_r# which are usually accompanied by a + 0xXX offset in some functions.
```

void Map2VRAM(ushort *puParm1,short *psParm2,uint uParm3,ushort uParm4)
{
    ushort uVar1;
    int in_r1;
    uint uVar2;
    uint uVar3;
    ushort uVar4;
    int in_r9;
    undefined4 uVar5;
    bool bVar6;
    
    uParm3 &= 0xffff;
    uVar2 = *(uint *)(in_r1 + 0xc);
    uVar4 = 0;
    uVar5 = *(undefined4 *)(in_r9 + 0x10);
    if (uParm4 == 0) {
        bVar6 = true;
    }
    else {
        bVar6 = false;
    }
    if (!bVar6) {
        do {
            uVar3 = 0;
            if (uParm3 == 0) {
                bVar6 = true;
            }
            else {
                bVar6 = false;
            }
            while (!bVar6) {
                uVar1 = *puParm1;
                if (true) {
                    puParm1 = (ushort *)((int)puParm1 + 1);
                }
                *psParm2 = (uVar1 | (ushort)((uVar2 & 0xf) << 0xc)) + (short)uVar5;
                uVar3 = uVar3 + 1 & 0xffff;
                if (uVar3 < uParm3) {
                    bVar6 = false;
                }
                else {
                    bVar6 = true;
                }
                psParm2 = psParm2 + 1;
            }
            uVar4 += 1;
            if (uVar4 < uParm4) {
                bVar6 = false;
            }
            else {
                bVar6 = true;
            }
            psParm2 = psParm2 + (0x40 - uParm3);
        } while (!bVar6);
    }
    return;
}
```

I was looking at C&C for the Saturn where there are a lot of class functions that have a lot of args but to hopefully simplify debugging this i tried to find functions that will have similar issues in the SDK(as it is unknown if anything is different compared to the info i have on the C&C PC counterpart so its probably not the best thing to examine in this case).
```
SCL_InitRotateTable
SCL_SetDisplayMode
SCL_SetAutoColChg
ex_keyword2
BPL_GetStmInfo
GFCD_GetLenData
GFS_GetFileSize
PCM_GetWriteBuf
Map2VRAM
gxSetMaterial
SND_CtrlDirMidi
GFS_GetFileSize
STM_GetInfo
FNT_Print256
BPL_GetStmInfo
MTH_Curve2
MPG_GetReport
MPG_SpGetTimeCode
SPR_3AllCoordTransClipPers
MPSYS_DoPlay
MPG_MvGetTimeCode
PCM_MeGetRingWrite
pcm_GetPcmWrite
```
should be ones that would have arg issues like these.

**Comment by VGKintsugi** [comment]
Thank you for the bug report, it will be 1-2 weeks before I have time to dig into this. 

Very likely I have mistakes/omissions in superh.pspec and superh.cspec. There's isn't much documentation on those file formats so I've been copying from other processor modules. 

I used https://gcc-renesas.com/manuals/SH-ABI-Specification.html, as a reference. It's also possible the Saturn uses a different calling convention.

**Comment by mumbel** [comment]
See ghidra issue 472 for spec docs

**Comment by VGKintsugi** [comment]
Thanks @mumbel, I will take a look.

**Comment by VGKintsugi** [comment]
@tomsons26, 

I have tried modifying the function prototype settings in the superh.cspec and unfortunately wasn't able to get it to work yet. When I built some sample code with GCC 6.2.2 the decompilation worked great as is (all args appeared correctly). 

Are you attempting to the compile the SDK source? What toolchain are using?

**Comment by tomsons26** [comment]
None, Map2VRAM was from the SDK's compiled version of the c, SCL_FUNC.O.
I see this stack issue all though C&C for the Saturn in every function that has more than 4 args so this is definitely not a one off.
I also tried https://github.com/will07c5/ghidra-sh , but its output is very incomplete currently, however it did seem to let me correct the args and did assign them in the decompilation correctly, bit hard to tell in the state its in so there's a possibility something in your sinc is off but this one might have it more correct.
I tried its cspec but the result was same so my feeling is its something in sinc.
One thing i'm wondering is if define register lines should be more split out

**Comment by VGKintsugi** [comment]
@tomsons26, 

I fixed a few more bugs in my sinc. I had a typo in "mov.l  @(disp,rm_04_07),rn_08_11", which now corrected allows for better decompilation. Here is an example function from Floupix that now decompiles correctly:

```
void FUN_06008800(undefined4 *puParm1,undefined4 uParm2,undefined4 uParm3,undefined4 uParm4,
                 undefined4 uParm5,undefined4 uParm6,undefined4 uParm7,undefined4 uParm8,
                 undefined4 uParm9,undefined4 uParm10)

{
  code *pcVar1;
  
  puParm1[3] = uParm5;
  puParm1[4] = uParm6;
  puParm1[5] = uParm7;
  puParm1[6] = uParm8;
  puParm1[7] = uParm9;
  pcVar1 = DAT_0600883c;
  puParm1[1] = uParm3;
  *puParm1 = uParm2;
  puParm1[2] = uParm4;
  (*pcVar1)(puParm1 + 8);
  *(undefined4 *)((int)puParm1 + (int)DAT_0600883a) = uParm10;
  return;
}

```

**Comment by tomsons26** [comment]
Yup that fixed it! Nice
