### ISSUE TITLE
Add Patterns

### ISSUE THREAD

**Issue by tomsons26** [VGKintsugi/Ghidra-SegaSaturn-Processor#2]
The patterns in the patternconstants.xml are used to enhance and speed up detection of various things, one of which is the function start.
Crude ones I've been using are
```
<patternlist>
  <pattern>
     <data>0x2F86</data> <!-- mov.l   r8, @-r15 -->
     <codeboundary/>
     <possiblefuncstart/>
  </pattern>
  <pattern>
     <data>0x2FE6</data> <!-- mov.l   r14, @-r15 -->
     <codeboundary/>
     <possiblefuncstart/>
  </pattern>
</patternlist>
```
but i have near no knowledge of SuperH so i dunno what else could be added.

**Comment by VGKintsugi** [comment]
I can look into adding this in as well.

**Comment by VGKintsugi** [comment]
Closing issue as I'm archiving the project now that the processor module has been merged to Ghidra trunk.
